language: node_js
node_js:
  - "node"
  - "lts/*"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run lint
  - npm run prepublishOnly
after_script:
  - npm run coverage
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
