language: node_js
node_js:
  - "lts/*"

stages:
  - test
  - coverage
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: npm test && npm run lint
    - stage: coverage
      script: npm run coverage && npm install coveralls && cat ./coverage/lcov.info | coveralls
    - stage: deploy
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
