language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules

stages:
  - test
  - coverage
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: npm test
    - script: npm run lint
      name: "Linting Test"
    - stage: coverage
      name: "Coverage Report"
      script: npm run coverage && npm install coveralls && cat ./coverage/lcov.info | coveralls
    - stage: deploy
      name: "Semantic Release"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
